application: proteator
version: 1
runtime: php55
api_version: 1

handlers:
- url: /style
  static_dir: style

- url: /scripts
  static_dir: scripts

- url: /img
  static_dir: img

- url: /manual.html
  script: manual.html

- url: /.*
  script: index.html